/**
 * Image Constants
 * Central location for all image imports organized by section.
 *
 * Image policy (keeps the site clear of copyright and "fake photo" problems):
 *  - Illustrations: original vector artwork generated by scripts/illustrations (npm run illustrations). They make no
 *    claim to show Vayu's own facility, team or customers.
 *  - Photos: only licensed files (CC0 / CC BY / CC BY-SA) with a registry entry in src/content/imageCredits.ts and a
 *    visible on-image credit. See /image-credits.
 *  - No AI-generated people, places or fake brands.
 */

import { IMAGE_CREDITS } from '@/content/imageCredits';
import type { ImageSlotData } from '@/components/site/ImageSlot';

// Logos
import logoMain from '@/assets/logo.png';
import logoHorizontal from '@/assets/logo-horizontal.png';
import logoHorizontalLight from '@/assets/logo-horizontal-light.png';

// Video
import factoryVideo from '@/assets/video/factory-top-view.mp4';

// Licensed photos (credits in src/content/imageCredits.ts)
import photoConveyor from '@/assets/photos/corrugated-conveyor.jpg';
import photoTester from '@/assets/photos/compression-tester.jpg';
import photoCloseup from '@/assets/photos/corrugated-closeup.jpg';

// Product illustrations
import prod3ply from '@/assets/illustrations/product-3-ply.svg';
import prod5ply from '@/assets/illustrations/product-5-ply.svg';
import prod7ply from '@/assets/illustrations/product-7-ply.svg';
import prodDieCut from '@/assets/illustrations/product-die-cut.svg';
import prodPrinted from '@/assets/illustrations/product-printed.svg';
import prodFood from '@/assets/illustrations/product-food-grade.svg';
import supTape from '@/assets/illustrations/product-bopp-tape.svg';
import supStretch from '@/assets/illustrations/product-stretch-film.svg';
import supBubble from '@/assets/illustrations/product-bubble-wrap.svg';
import supStrap from '@/assets/illustrations/product-pp-strapping.svg';

// Industry, process and about illustrations
import indEcom from '@/assets/illustrations/industry-ecommerce.svg';
import indFmcg from '@/assets/illustrations/industry-fmcg.svg';
import indElectronics from '@/assets/illustrations/industry-electronics.svg';
import indFood from '@/assets/illustrations/industry-food.svg';
import indPharma from '@/assets/illustrations/industry-pharma.svg';
import indAuto from '@/assets/illustrations/industry-auto.svg';
import procSpec from '@/assets/illustrations/process-spec.svg';
import procDispatch from '@/assets/illustrations/process-dispatch.svg';
import aboutHero from '@/assets/illustrations/about-hero.svg';

// Blog illustrations
import blogDefault from '@/assets/illustrations/blog-default.svg';
import blogTypes from '@/assets/illustrations/blog-types.svg';
import blogWalls from '@/assets/illustrations/blog-walls.svg';
import blogGsm from '@/assets/illustrations/blog-gsm.svg';
import blogBurst from '@/assets/illustrations/blog-burst-ect.svg';
import blogMeasure from '@/assets/illustrations/blog-measure.svg';
import blogKraft from '@/assets/illustrations/blog-kraft.svg';
import blogTool from '@/assets/illustrations/blog-3d-tool.svg';

/** Every illustration is authored at 4:3 (1200×900); blog art at 16:9 (1600×900). */
const SIZE_43 = { width: 1200, height: 900 } as const;
const SIZE_169 = { width: 1600, height: 900 } as const;

// ============================================
// LOGO IMAGES
// ============================================
export const LOGO_IMAGES = {
  main: logoMain,
  horizontal: logoHorizontal,
  /** Transparent, light-text variant for ink (dark) backgrounds */
  horizontalLight: logoHorizontalLight,
} as const;

// ============================================
// VIDEO ASSETS
// ============================================
// VERIFY-LATER[IMG-07]: provenance of factory-top-view.mp4 is unknown (may be AI-generated or stock). Confirm the owner made it or has a licence, otherwise remove it.
export const VIDEO_ASSETS = {
  factoryTour: factoryVideo,
} as const;

// ============================================
// PRODUCT IMAGES (original illustrations)
// ============================================
/** Index order is relied on by content/home.ts and content/products.ts: 0 3-ply, 1 5-ply, 2 7-ply, 3 die-cut, 4 printed, 5 food-grade */
export const PRODUCT_IMAGES = [
  { id: 'PROD-1', src: prod3ply, alt: 'Illustration of kraft 3-ply corrugated boxes stacked, one open, with a board cross-section', ...SIZE_43 },
  { id: 'PROD-2', src: prod5ply, alt: 'Illustration of double-wall 5-ply corrugated cartons stacked, one open', ...SIZE_43 },
  { id: 'PROD-3', src: prod7ply, alt: 'Illustration of a heavy-duty 7-ply box strapped on a pallet', ...SIZE_43 },
  { id: 'PROD-4', src: prodDieCut, alt: 'Illustration of a die-cut corrugated mailer: flat dieline beside the assembled box', ...SIZE_43 },
  { id: 'PROD-5', src: prodPrinted, alt: 'Illustration of printed corrugated boxes with plain brand-colour graphics', ...SIZE_43 },
  { id: 'PROD-6', src: prodFood, alt: 'Illustration of a ventilated kraft corrugated box with fresh produce', ...SIZE_43 },
] as const;

export const SUPPLY_IMAGES = {
  'bopp-tape': { src: supTape, alt: 'Illustration of a roll of BOPP packing tape', ...SIZE_43 },
  'stretch-film': { src: supStretch, alt: 'Illustration of a roll of stretch film', ...SIZE_43 },
  'bubble-wrap': { src: supBubble, alt: 'Illustration of a bubble wrap sheet', ...SIZE_43 },
  'pp-strapping': { src: supStrap, alt: 'Illustration of a coil of polypropylene strapping', ...SIZE_43 },
} as const;

// ============================================
// INDUSTRY IMAGES (original illustrations)
// ============================================
export const INDUSTRY_IMAGES = {
  'e-commerce': { src: indEcom, alt: 'Illustration of a taped shipping carton with a courier label beside a green mailer box', ...SIZE_43 },
  fmcg: { src: indFmcg, alt: 'Illustration of a pallet of stacked cartons wrapped in stretch film', ...SIZE_43 },
  electronics: { src: indElectronics, alt: 'Illustration of an electronics carton with foam corner protectors around a laptop', ...SIZE_43 },
  'food-beverage': { src: indFood, alt: 'Illustration of a ventilated kraft box with fresh produce', ...SIZE_43 },
  pharma: { src: indPharma, alt: 'Illustration of a clean white carton with a medical cross beside vials', ...SIZE_43 },
  automotive: { src: indAuto, alt: 'Illustration of a heavy-duty carton on a pallet with a gear marking and corner protectors', ...SIZE_43 },
} as const;

// ============================================
// PROCESS STEP IMAGES (home page "Dieline to Dispatch")
// ============================================
export const PROCESS_IMAGES: Record<'spec' | 'convert' | 'qc' | 'dispatch', ImageSlotData> = {
  spec: { id: 'home.process.spec', src: procSpec, alt: 'Illustration of a carton dieline with length, breadth and height marked', kind: 'illustration', ...SIZE_43 },
  convert: {
    id: 'home.process.convert',
    src: photoConveyor,
    alt: 'Stacked corrugated board sheets on a roller conveyor in a converting plant',
    kind: 'photo-credited',
    credit: IMAGE_CREDITS['corrugated-conveyor'],
    focal: { x: 0.4, y: 0.6 },
    width: 1400,
    height: 1050,
  },
  qc: {
    id: 'home.process.qc',
    src: photoTester,
    alt: 'A box compression tester, the machine used to measure how much load a carton can take',
    kind: 'photo-credited',
    credit: IMAGE_CREDITS['compression-tester'],
    width: 1200,
    height: 900,
  },
  dispatch: { id: 'home.process.dispatch', src: procDispatch, alt: 'Illustration of a delivery truck beside a pallet of boxes ready to load', kind: 'illustration', ...SIZE_43 },
};

// ============================================
// ABOUT PAGE
// ============================================
export const ABOUT_IMAGES = {
  main: aboutHero,
  alt: 'Illustration of warehouse racking stacked with cartons',
  ...SIZE_43,
} as const;

// ============================================
// BLOG IMAGES
// ============================================
export const BLOG_IMAGES = {
  defaultThumbnail: blogDefault,
  'BLOG-01-thumbnail': blogTypes, // types-of-corrugated-boxes
  'BLOG-02-thumbnail': blogWalls, // corrugated-wall-differences
  'BLOG-03-thumbnail': photoCloseup, // flute-types-guide (photo, credited below)
  'BLOG-04-thumbnail': blogGsm, // gsm-calculation-strength
  'BLOG-05-thumbnail': blogBurst, // burst-strength-ect-guide
  'BLOG-06-thumbnail': blogMeasure, // box-measurements-guide
  'BLOG-07-thumbnail': blogKraft, // kraft-paper-grades
  'BLOG-08-thumbnail': blogTool, // 3d-box-designer-tool-free
  alt: 'Vayu Packaging Solutions: corrugated boxes and packaging',
} as const;

/** Credits for blog thumbnails that are third-party photos (the rest are our own illustrations) */
export const BLOG_IMAGE_CREDITS = {
  'BLOG-03-thumbnail': IMAGE_CREDITS['corrugated-closeup'],
} as const;

export const BLOG_IMAGE_SIZES = { photo: { width: 1400, height: 1050 }, illustration: SIZE_169 } as const;
